"""Shared Modal setup: one image and one runner, reused by every app.

Each experiment gets its own :class:`modal.App` (see ``deploy/app_*.py``) so the
six can run concurrently on separate GPUs and be started, watched and stopped
independently -- one failing experiment then does not take the others with it.
Everything they have in common lives here.
"""

from __future__ import annotations

import pathlib

import modal

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUTPUT_DIR = "/outputs"

#: Prefix the examples read their overrides under. Kept in one place: preset
#: keys are written bare and prefixed on the way out, so the two cannot drift
#: apart -- writing them prefixed by hand is exactly how a preset silently
#: stops applying.
ENV_PREFIX = "XWM_"

#: Default accelerator. Ample for 128px raytracing plus a 384-wide ViT.
GPU = "A10G"

# Newton needs GitPython to fetch robot assets and trimesh/pycollada to read the
# Franka URDF's meshes; none of them are Newton install-time requirements.
image = (
    modal.Image.debian_slim(python_version="3.12")
    .apt_install("git", "libgl1", "libglib2.0-0", "libgomp1")
    .pip_install(
        "jax[cuda12]>=0.11,<0.12",
        "equinox>=0.11.8",
        "optax>=0.2.4",
        "numpy>=1.26",
        "einops>=0.8.0",
        "matplotlib>=3.8",
        "pillow>=10.0",
        "newton>=1.5",
        "warp-lang>=1.16",
        "GitPython>=3.1",
        "trimesh>=4.0",
        "pycollada>=0.8",
        "usd-core>=25.0",
    )
    # OVRTX gives the path-traced quality of Newton's own documentation renders.
    # Optional and NVIDIA-only, so a failure here degrades figures rather than
    # breaking the image.
    .run_commands(
        'pip install ovrtx || echo "ovrtx unavailable; high-quality renders '
        'will fall back to the USD backend"'
    )
    # ViewerRTX imports pyglet for its camera vector maths even headless, where
    # there is no window and no display server. Deliberately its own layer
    # *after* OVRTX: a change here would otherwise invalidate that layer and
    # rebuild a 1.7 GB wheel from source.
    .pip_install("pyglet>=2.0")
    # OVRTX is a Vulkan application, and a CUDA container is not automatically a
    # Vulkan one. Two pieces are needed on top of the driver Modal injects: the
    # loader, and an ICD manifest telling it where the NVIDIA implementation
    # lives -- the driver ships the library but the manifest is generated by the
    # host installer, so in a container it has to be written by hand. Without it
    # OVRTX fails late and opaquely, with "createDevices failed".
    .apt_install(
        "libvulkan1",
        "libopengl0",  # libOpenGL.so.0, which OVRTX's USD resolver plugin links
        "vulkan-tools",  # vulkaninfo, for app_render.py::vulkan_probe
        # Omniverse links these even headless.
        "libx11-6", "libxcb1", "libxrandr2", "libxinerama1", "libxcursor1",
        "libxi6", "libsm6", "libice6", "libfreetype6",
    )
    .run_commands(
        "mkdir -p /usr/share/vulkan/icd.d",
        'printf \'{"file_format_version":"1.0.0","ICD":'
        '{"library_path":"libGLX_nvidia.so.0","api_version":"1.3.242"}}\''
        " > /usr/share/vulkan/icd.d/nvidia_icd.json",
    )
    # vulkan-tools drags in Mesa's software ICDs (llvmpipe, Intel, AMD), none of
    # which support hardware ray tracing. Pinning the loader to the NVIDIA
    # manifest keeps OVRTX from enumerating a CPU rasteriser and concluding the
    # machine has no ray-tracing GPU. Both names are set: VK_DRIVER_FILES is the
    # current one, VK_ICD_FILENAMES the name older loaders read.
    .env(
        {
            "VK_DRIVER_FILES": "/usr/share/vulkan/icd.d/nvidia_icd.json",
            "VK_ICD_FILENAMES": "/usr/share/vulkan/icd.d/nvidia_icd.json",
            # A GPU container defaults to compute+utility, and NVIDIA's Vulkan
            # implementation refuses to initialise without the graphics
            # capability -- which is why the loader can open the ICD but gets a
            # null vkCreateInstance back from it.
            "NVIDIA_DRIVER_CAPABILITIES": "all",
            # JAX preallocates ~75% of device memory on first use. These
            # experiments run JAX and Warp/MuJoCo in one process, so that pool
            # starves the physics engine and, worse, leaves no room outside it
            # to load a later JAX executable's CUBIN -- which is exactly how
            # MuZero died at iteration ~20 with RESOURCE_EXHAUSTED while
            # compiling its MCTS step. Allocating on demand costs a little
            # speed and some fragmentation risk; running out of memory costs
            # the whole run.
            "XLA_PYTHON_CLIENT_PREALLOCATE": "false",
        }
    )
    # mujoco_warp is not on PyPI and is optional: FrankaEnv(solver="auto") falls
    # back to Featherstone if this layer fails, so a broken upstream commit
    # degrades the run rather than breaking the image.
    #
    # Pin mujoco to what Newton 1.5 declares (~=3.11). Installing mujoco_warp
    # unpinned pulls 3.12, and Newton's MuJoCo kernels then fail to compile
    # against the drifted API -- the run still completes, but silently on
    # Featherstone, which is not the solver you asked for.
    .run_commands(
        "pip install 'mujoco~=3.11.0' && "
        "pip install --no-deps git+https://github.com/google-deepmind/mujoco_warp.git@v3.11.0 || "
        'echo "mujoco_warp unavailable; falling back to Featherstone"'
    )
    .env({"WARP_CACHE_PATH": "/tmp/warp-cache", "MPLBACKEND": "Agg"})
    # Modal 1.x does not auto-mount local Python modules, so this module has to
    # ship itself: the app files import it for `execute`.
    .add_local_python_source("_shared")
    .add_local_dir(ROOT / "xwm", remote_path="/root/xwm")
    .add_local_dir(
        ROOT / "examples",
        remote_path="/root/examples",
        ignore=["outputs", "__pycache__"],
    )
)

#: Fidelity presets. ``cpu-parity`` reproduces the laptop run so a GPU result can
#: be compared against it without confounding the hardware and the settings.
PRESETS: dict[str, dict[str, str]] = {
    "cpu-parity": {},
    "gpu": {
        "IMG_SIZE": "128",
        "PATCH_SIZE": "16",
        "N_TRAIN": "2048",
        "N_TEST": "256",
        "PRETRAIN_STEPS": "4000",
        "DYNAMICS_STEPS": "6000",
        "STEPS": "4000",
        "BATCH": "64",
        "DYN_BATCH": "32",
        "PLAN_EPISODES": "32",
        "PLAN_SAMPLES": "512",
        "ENC_DEPTH": "6",
        "ENC_DIM": "384",
        "ENC_HEADS": "6",
        "DYN_DEPTH": "6",
        "DYN_DIM": "384",
        "DYN_HEADS": "6",
        "SHADOWS": "true",
        "TEXTURES": "true",
        "SOLVER": "auto",
        # Path-traced figures: seconds per frame, so worth it only on a GPU.
        "RTX": "1",
        "RTX_SIZE": "768",
        # Reward-driven families: more interaction and a bigger search.
        "ITERATIONS": "120",
        "SEED_EPISODES": "200",
        "STEPS_PER_ITER": "100",
        "EPISODES_PER_ITER": "8",
        "EPISODE_LEN": "20",
        "LATENT_DIM": "256",
        "HIDDEN_DIM": "512",
        "PLAN_ITERS": "6",
        "SIMULATIONS": "64",
        "EVAL_EPISODES": "24",
    },
    "xl": {
        "IMG_SIZE": "224",
        "PATCH_SIZE": "16",
        "CLIP_LEN": "10",
        "N_TRAIN": "4096",
        "N_TEST": "512",
        "PRETRAIN_STEPS": "12000",
        "DYNAMICS_STEPS": "16000",
        "STEPS": "12000",
        "BATCH": "64",
        "DYN_BATCH": "16",
        "PLAN_EPISODES": "48",
        "PLAN_SAMPLES": "1024",
        "ENC_DEPTH": "12",
        "ENC_DIM": "384",
        "ENC_HEADS": "6",
        "DYN_DEPTH": "6",
        "DYN_DIM": "384",
        "DYN_HEADS": "6",
        "SHADOWS": "true",
        "TEXTURES": "true",
        "SOLVER": "auto",
        "RTX": "1",
        "RTX_SIZE": "1024",
        "ITERATIONS": "400",
        "SEED_EPISODES": "500",
        "STEPS_PER_ITER": "200",
        "EPISODES_PER_ITER": "8",
        "EPISODE_LEN": "25",
        "LATENT_DIM": "512",
        "HIDDEN_DIM": "512",
        "PLAN_ITERS": "8",
        "SIMULATIONS": "128",
        "EVAL_EPISODES": "32",
    },
}

#: experiment name -> example script stem.
EXPERIMENTS = {
    "image": "01_image_ijepa",
    "video": "02_video_vjepa",
    "collapse": "03_collapse_strategies",
    "action": "04_action_world_model",
    "planning": "05_planning",
    "franka": "06_franka_newton",
    "tdmpc2": "07_tdmpc2_franka",
    "muzero": "08_muzero_franka",
}


def volume_for(experiment: str) -> modal.Volume:
    """A volume per experiment, so concurrent runs cannot clobber each other."""
    return modal.Volume.from_name(f"xwm-outputs-{experiment}", create_if_missing=True)


def report_device() -> None:
    """Print what we actually got, rather than assuming the GPU is there."""
    import subprocess

    try:
        smi = subprocess.run(  # noqa: S603
            ["nvidia-smi", "--query-gpu=name,memory.total,driver_version",
             "--format=csv,noheader"],
            capture_output=True, text=True, check=False,
        )
        print(f"nvidia-smi: {smi.stdout.strip() or smi.stderr.strip()}", flush=True)
    except FileNotFoundError:
        print("nvidia-smi: not found", flush=True)

    import jax

    print(f"jax {jax.__version__} devices: {jax.devices()}", flush=True)
    import warp as wp

    wp.init()
    print(f"warp {wp.__version__} device: {wp.get_device()}", flush=True)
    try:
        import mujoco_warp  # noqa: F401

        print("mujoco_warp: available (SolverMuJoCo enabled)", flush=True)
    except ImportError:
        print("mujoco_warp: unavailable (falling back to Featherstone)", flush=True)


def execute(experiment: str, preset: str) -> dict:
    """Run one experiment's example script and return a result record."""
    import os
    import subprocess
    import sys
    import time

    if preset not in PRESETS:
        raise ValueError(f"unknown preset {preset!r}; choose from {sorted(PRESETS)}")
    script = EXPERIMENTS[experiment]
    overrides = PRESETS[preset]

    report_device()
    print(f"\npreset {preset!r} -> {overrides or '(defaults)'}", flush=True)
    print(f"{'=' * 72}\n== {experiment} ({script})\n{'=' * 72}", flush=True)

    # PYTHONPATH, not cwd: Python puts the *script's* directory on sys.path, so
    # /root/examples is importable but /root (where xwm lives) is not.
    environment = {
        **os.environ,
        **{f"{ENV_PREFIX}{k}": v for k, v in overrides.items()},
        f"{ENV_PREFIX}OUTPUT_ROOT": OUTPUT_DIR,
        "PYTHONPATH": "/root",
    }
    start = time.time()
    # Streamed line by line rather than captured. A captured run is invisible
    # until it exits, which on a multi-hour training job means no way to tell
    # slow from hung -- and stderr merged into stdout so a traceback arrives in
    # place rather than after everything else.
    process = subprocess.Popen(  # noqa: S603
        [sys.executable, "-u", f"/root/examples/{script}.py"],
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        text=True,
        bufsize=1,
        cwd="/root",
        env=environment,
    )
    for line in process.stdout or ():
        sys.stdout.write(line)
        sys.stdout.flush()
    returncode = process.wait()
    return {
        "experiment": experiment,
        "script": script,
        "preset": preset,
        "returncode": returncode,
        "seconds": round(time.time() - start, 1),
    }


def collect_files() -> dict[str, bytes]:
    """Read every artifact out of the mounted volume."""
    root = pathlib.Path(OUTPUT_DIR)
    return {
        str(path.relative_to(root)): path.read_bytes()
        for path in sorted(root.rglob("*"))
        if path.is_file()
    }


def download(files: dict[str, bytes]) -> int:
    """Write collected artifacts into ``examples/outputs/``."""
    target = ROOT / "examples" / "outputs"
    for name, blob in files.items():
        path = target / name
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(blob)
    return len(files)
