"""Plan with a learned world model, and check it against honest baselines.

This is the full pipeline and the point of the whole library:

1. Learn a representation from passive observation (LeJEPA, no actions).
2. Freeze it and learn action-conditioned latent dynamics.
3. Given a *goal image*, search for an action sequence whose imagined rollout
   ends near the goal's embedding -- never rendering a pixel.
4. Execute those actions in the real environment and measure the *true*
   distance to the goal.

Step 4 is the part that makes this an evaluation rather than a demo. Latent cost
going down proves nothing: the planner optimises latent cost by construction,
so a model with a broken representation will report confident, meaningless
plans. The numbers below are ground-truth positions the model never sees,
compared against three baselines:

* **no-op**  -- do nothing. Distance from start to goal.
* **random** -- random actions of the same magnitude.
* **oracle** -- the action sequence that actually generated the goal.

Goals are generated by rolling the real world forward, so every goal is exactly
reachable, and distractors are held still during evaluation so the goal is
well-defined.

Run: python examples/05_planning.py
"""

import equinox as eqx
import jax.numpy as jnp
import jax.random as jr
from _common import report, setting, setup

import xwm

IMG_SIZE = setting("IMG_SIZE", 32)
PATCH_SIZE = setting("PATCH_SIZE", 4)
FRAMES = setting("CLIP_LEN", 9)
PRETRAIN_STEPS = setting("PRETRAIN_STEPS", 300)
DYNAMICS_STEPS = setting("DYNAMICS_STEPS", 500)
HORIZON = setting("PLAN_HORIZON", 6)
EPISODES = setting("PLAN_EPISODES", 32)
PLAN_SAMPLES = setting("PLAN_SAMPLES", 512)
ENC = {
    "depth": setting("ENC_DEPTH", 4),
    "embed_dim": setting("ENC_DIM", 128),
    "num_heads": setting("ENC_HEADS", 4),
}
DYN = {
    "depth": setting("DYN_DEPTH", 4),
    "pred_dim": setting("DYN_DIM", 128),
    "num_heads": setting("DYN_HEADS", 4),
}


def train_world_model(key, world):
    k_data, k_enc, k_dyn = jr.split(key, 3)
    images = xwm.data.sprite_images(jr.fold_in(k_data, 0), 2048, world=world)["image"]
    clips = xwm.data.sprite_sequences(jr.fold_in(k_data, 1), 512, FRAMES, world=world)

    encoder_model = xwm.families.jepa.lejepa(
        key=k_enc, img_size=IMG_SIZE, patch_size=PATCH_SIZE, n_targets=4,
        encoder_kwargs=ENC, predictor_kwargs={"depth": 3, "pred_dim": 64, "num_heads": 4},
        reg_weight=20.0,
    )
    trainer = xwm.training.Trainer(
        encoder_model,
        xwm.training.adamw(
            xwm.training.cosine_warmup(1e-3, PRETRAIN_STEPS, warmup_steps=PRETRAIN_STEPS // 10)
        ),
    )
    state, hist = trainer.fit(
        xwm.data.iter_batches({"image": images}, 32, key=k_enc, epochs=None),
        steps=PRETRAIN_STEPS, key=k_enc, log_every=PRETRAIN_STEPS,
    )
    print(f"  stage 1 (encoder):  loss {hist[-1]['loss']:.4f}")

    model = xwm.families.jepa.action_world_model(
        key=k_dyn, action_dim=world.action_dim, encoder=state.model.encoder,
        freeze_encoder=True, conditioning="both",
        dynamics_kwargs=DYN,
    )
    trainer = xwm.training.Trainer(
        model,
        xwm.training.adamw(
            xwm.training.cosine_warmup(1e-3, DYNAMICS_STEPS, warmup_steps=DYNAMICS_STEPS // 10)
        ),
    )
    state, hist = trainer.fit(
        xwm.data.iter_batches(
            {"video": clips["video"], "action": clips["action"]}, 16, key=k_dyn, epochs=None
        ),
        steps=DYNAMICS_STEPS, key=k_dyn, log_every=DYNAMICS_STEPS,
    )
    print(
        f"  stage 2 (dynamics): teacher-forcing {hist[-1]['loss_teacher_forcing']:.4f}  "
        f"rollout {hist[-1]['loss_rollout']:.4f}"
    )
    return state.model


def episode_actions(key, world):
    """A smooth, bounded action sequence of length ``HORIZON``."""
    return xwm.data.random_actions(key, 1, HORIZON, world.action_dim, smoothness=0.5)[0]


def make_episode(k_reset, k_actions, world):
    """A start state and an exactly-reachable goal, with distractors held still.

    The goal is produced by *executing* an action sequence, so that sequence is
    an oracle solution and the goal is guaranteed achievable.
    """
    start = world.reset(k_reset)
    actions = episode_actions(k_actions, world)
    state = start
    for a in actions:
        state = world.step(state, a)  # no key -> distractors frozen
    return start, state, actions


def execute(world, state, actions):
    for a in actions:
        state = world.step(state, a)
    return state


def distance(state, goal_pos):
    """True Euclidean distance between agent positions -- never seen by the model."""
    return float(jnp.linalg.norm(state.pos - goal_pos))


def frames_of(world, state, actions):
    """Render a trajectory for visualisation (evaluation only)."""
    frames = [world.render(state)]
    for a in actions:
        state = world.step(state, a)
        frames.append(world.render(state))
    return jnp.stack(frames)


def main():
    out = setup("05_planning", n_series=4)
    key = jr.PRNGKey(0)
    k_train, k_eval = jr.split(key)
    world = xwm.data.SpriteWorld(IMG_SIZE, n_distractors=2)

    print("training the world model", flush=True)
    model = train_world_model(k_train, world)

    dynamics = model.dynamics_fn()
    encode = eqx.filter_jit(model.encode)
    planner = xwm.planning.CEM(
        HORIZON, world.action_dim, n_samples=PLAN_SAMPLES,
        n_elites=max(8, PLAN_SAMPLES // 8), n_iters=8,
        low=-1.0, high=1.0, init_std=0.6,
    )

    @eqx.filter_jit
    def plan(k, z0, z_goal):
        return planner.plan(k, dynamics, z0, xwm.planning.goal_cost(z_goal, kind="l2"))

    print(
        f"\nplanning with CEM (horizon {HORIZON}, {planner.n_samples} samples, "
        f"{planner.n_iters} iters) over {EPISODES} episodes",
        flush=True,
    )
    results = {"no-op": [], "random": [], "planner": [], "oracle": []}
    strips = None
    for i in range(EPISODES):
        # Split every purpose off one key explicitly. Deriving them ad hoc is a
        # trap: `jr.fold_in(k, 1)` and `jr.split(k)[1]` are the *same* key, so a
        # "random" baseline built that way silently becomes the oracle sequence.
        k_reset, k_oracle, k_plan, k_random = jr.split(jr.fold_in(k_eval, i), 4)
        start, goal_state, oracle = make_episode(k_reset, k_oracle, world)
        z0 = encode(world.render(start))
        z_goal = encode(world.render(goal_state))

        actions = plan(k_plan, z0, z_goal).actions
        random = episode_actions(k_random, world)

        target = goal_state.pos
        results["no-op"].append(distance(start, target))
        results["random"].append(distance(execute(world, start, random), target))
        results["planner"].append(distance(execute(world, start, actions), target))
        results["oracle"].append(distance(execute(world, start, oracle), target))

        if i == 0:  # keep the first episode for the animation
            strips = {
                "planner": frames_of(world, start, actions),
                "oracle": frames_of(world, start, oracle),
                "random": frames_of(world, start, random),
                "goal": jnp.broadcast_to(
                    world.render(goal_state)[None], (HORIZON + 1, *world.observation_shape)
                ),
            }

    print("\ntrue distance to the goal position (lower is better):")
    print(f"  {'policy':<10}{'mean':>8}{'median':>8}{'worst':>8}")
    for name in ("no-op", "random", "planner", "oracle"):
        v = jnp.asarray(results[name])
        print(f"  {name:<10}{float(jnp.mean(v)):>8.3f}{float(jnp.median(v)):>8.3f}"
              f"{float(jnp.max(v)):>8.3f}")

    gap = float(jnp.mean(jnp.asarray(results["no-op"])))

    def closed(name):
        return 100.0 * (1.0 - float(jnp.mean(jnp.asarray(results[name]))) / gap)

    print(
        f"\nplanner closes {closed('planner'):.0f}% of the initial gap; "
        f"random {closed('random'):.0f}%, oracle {closed('oracle'):.0f}%"
    )

    # -- artifacts ----------------------------------------------------------
    print("\nartifacts:")
    policies = ["no-op", "random", "planner", "oracle"]
    ax = xwm.plots.plot_bars(
        policies,
        [float(jnp.mean(jnp.asarray(results[p]))) for p in policies],
        ylabel="mean true distance to goal (lower is better)",
        title=f"Goal reaching over {EPISODES} episodes, horizon {HORIZON}",
    )
    report(xwm.plots.save_figure(ax.figure, out / "policy_comparison.png"))

    import matplotlib.pyplot as plt

    fig, ax = plt.subplots(figsize=(5.6, 5))
    initial = jnp.asarray(results["no-op"])
    limit = float(jnp.max(initial)) * 1.05
    ax.plot([0, limit], [0, limit], color="#999999", linewidth=1, linestyle="--",
            label="no better than doing nothing")
    for i, policy in enumerate(["random", "planner"]):
        style = xwm.plots.series_style(i, 2, xwm.plots.CURVE_PALETTE)
        style["linestyle"] = "None"
        style["markersize"] = 7
        ax.plot(initial, jnp.asarray(results[policy]), label=policy, **style)
    ax.set_xlabel("initial distance to goal")
    ax.set_ylabel("final distance to goal")
    ax.set_title("Points below the dashed line made progress")
    ax.grid(axis="both", visible=True)
    ax.legend(loc="upper left")
    report(xwm.plots.save_figure(fig, out / "per_episode.png"))

    if strips is not None:
        order = ["goal", "planner", "oracle", "random"]
        report(
            xwm.plots.save_gif(
                out / "planning_episode.gif",
                [strips[k] for k in order],
                labels=order,
                fps=3,
                scale=5,
            )
        )

    rows = []
    for policy in policies:
        v = jnp.asarray(results[policy])
        rows.append(
            [policy, float(jnp.mean(v)), float(jnp.median(v)), float(jnp.max(v)), closed(policy)]
        )
    report(
        xwm.plots.save_table(
            out / "results",
            ["policy", "mean", "median", "worst", "% of gap closed"],
            rows,
            caption=(
                f"True distance to the goal after {HORIZON} steps, {EPISODES} episodes. "
                "The planner optimises a latent cost and never sees these positions."
            ),
            label="tab:planning",
        )
    )


if __name__ == "__main__":
    main()
